use upstream yaml parser
ros-simulation/gazebo_ros2_control pull request #60
Opened 2021-02-17 02:52 UTC by Karsten1987

fixes #59 

With this PR, the actual parameters are being set:

```
 ➭ ros2 param list
...
/controller_manager:
  joint_state_controller.type
  joint_trajectory_controller.type
  update_rate
  use_sim_time
```

While implementing this, I found actually a second bug in which all specified controllers in the loaded yaml file would be loaded. It didn't show in the example, however this would necessarily lead to resource conflicts when more than one controller use the same command interface.

2021-02-17 14:58 UTC, ahcorde requested changes
@Karsten1987 I was testing your contribution but I was not able to run the example or get the `/joint_states`. You didn't launch the controllers.

2021-02-17 14:58 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
> +  }
```suggestion
  std::vector<std::string> start_controllers = {};
  std::vector<std::string> stop_controllers = {};
  auto parameter_map = rclcpp::parameter_map_from(params_struct);
  rcl_yaml_node_struct_fini(params_struct);
  auto it = parameter_map.find("/controller_manager");
  if (it != parameter_map.end()) {
    for (auto param : it->second) {
      if (param.get_name() == "update_rate") {
        // Decide the plugin control period
        impl_->control_period_ = rclcpp::Duration(
          std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::duration<double>(
              1.0 / static_cast<double>(param.get_value_message().integer_value))));

        // Check the period against the simulation period
        if (impl_->control_period_ < gazebo_period) {
          RCLCPP_ERROR_STREAM(
            impl_->model_nh_->get_logger(),
            "Desired controller update period (" << impl_->control_period_.seconds() <<
              " s) is faster than the gazebo simulation period (" <<
              gazebo_period.seconds() << " s).");
        } else if (impl_->control_period_ > gazebo_period) {
          RCLCPP_WARN_STREAM(
            impl_->model_nh_->get_logger(),
            " Desired controller update period (" << impl_->control_period_.seconds() <<
              " s) is slower than the gazebo simulation period (" <<
              gazebo_period.seconds() << " s).");
        }
      }
      else {
        std::string controller_name = param.get_name();
        std::string controller_type = param.as_string();
        std::size_t found = controller_name.find(".");
        if (found != std::string::npos) {
          controller_name = controller_name.substr(0, found);
        }

        auto controller = impl_->controller_manager_->load_controller(
          controller_name,
          controller_type);

        auto it_controller = parameter_map.find("/"+controller_name);
        if (it_controller != parameter_map.end()) {
          controller->get_node()->set_parameters(it_controller->second);
        }
        impl_->controllers_.push_back(controller);
        controller->configure();
        start_controllers.push_back(controller_name);
      }
    }
```

2021-02-17 14:58 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
> +
```suggestion
  auto switch_future = std::async(
    std::launch::async,
    &controller_manager::ControllerManager::switch_controller,
    impl_->controller_manager_,
    start_controllers, stop_controllers,
    2, true, rclcpp::Duration(0, 0));  // STRICT_: 2
  while (std::future_status::timeout == switch_future.wait_for(std::chrono::milliseconds(100))) {
    impl_->controller_manager_->update();
  }
  controller_interface::return_type result = switch_future.get();
  if (result != controller_interface::return_type::SUCCESS) {
    RCLCPP_ERROR(impl_->model_nh_->get_logger(), "Error initializing the joint_state_controller");
  }
```

2021-02-17 15:23 UTC, Karsten1987 commented
> You didn't launch the controllers.

That's on purpose. As mentioned above, not all controllers can be loaded/configured at the same time due to resource conflicts. Also I believe it's not good practice to launch them within the gazebo plugin. I'd rather use either the spawner functionality (once available) or load them explicitly via services through a launch file.

2021-02-17 15:26 UTC, ahcorde commented
I will have a look to the PR https://github.com/ros-controls/ros2_control/pull/310

anyhow the conditional to get the `udpate_rate` is required.

2021-02-17 17:47 UTC, Karsten1987 commented
you don't necessarily need the spawner PR. You should be able to use `ros2 control load_start_controller` in the launch file to start the controllers.

2021-02-18 01:28 UTC, Karsten1987 commented
> anyhow the conditional to get the udpate_rate is required.

done in 1047c22

2021-02-18 09:45 UTC, ahcorde commented
@Karsten1987 

I was testing the `ros2 control` commands. I was able to start the `joint_state_controller`

```bash
ros2 control load_start_controller joint_trajectory_controller` 
``` 

But I'm not able to load the `joint_trajectory_controller`. Digging about what it's happening here. The `/joint_trajectory_controller` parameters are not set.

```bash
ros2 param get /joint_trajectory_controller  joints
String values are: []
```

You should set up the parameters for the controller in the code.

2021-02-24 02:29 UTC, Karsten1987 commented
There's currently no clear way to set parameters to a gazebo plugin's node. So I had to do this manually by parsing the ros parameter's file and add the arguments to the node's context. That's certainly not a recommended way, but the only feasible at the moment.

/cc @chapulina @jacobperron

2021-02-28 04:17 UTC, joshnewans commented
I just wanted to add my 2c and say that as someone fairly new to all this, I found it quite confusing that the plugin loaded my controllers on its own as I expected a flow similar to my real robot where I used `ros2 control load_start_controller xxx`. The new behaviour resulting from this PR seemed more intuitive to me.

This PR resolved an issue I was having where the `controller_manager` and its child controllers did not obey the `use_sim_time` parameter I specified in the yaml file (and as I understand it there is currently no way to globally enable `use_sim_time`).

2021-03-01 17:07 UTC, Karsten1987 commented
@ahcorde friendly ping.

2021-03-02 10:07 UTC, ahcorde commented
I created a PR which builds on top of this PR load the controllers in the launch files: https://github.com/ros-simulation/gazebo_ros2_control/pull/64

2021-03-02 17:02 UTC, ahcorde approved these changes

2021-03-03 06:49 UTC, merged