Ensure that sim_joints_ always has the same number of elements as the…
ros-simulation/gazebo_ros2_control pull request #77
Opened 2021-05-25 21:23 UTC by kbogert

… joint_names

Otherwise a segfault occurs when some joints are not simulated by gazebo.

Possbily the cause of #67

2021-05-26 21:45 UTC, ahcorde requested changes
I'm not sure about adding a nullptr to the vector. This is happening because the joint_name doesn't exist, maybe it's because your configuration is wrong? or is there any specific use case for this ?

2021-05-26 21:57 UTC, kbogert commented
This is happening because there are joints in the urdf file that are not simulated by gazebo, there are lots of reasons why this could be the case (in our case, it's due to hacks needed to get parallel grippers to move correctly).

The alternative is to remove these joints from all of the vectors, reducing their size as the non-simulated joints are discovered.  This is do-able but much more complicated, and as far as I can tell having the nulls in the sim_joints vector isn't causing any issues.

2021-05-26 21:59 UTC, ahcorde requested changes

2021-05-26 21:59 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_system.cpp
> +    if (this->dataPtr->sim_joints_[j]) {
This indentation looks wrong

2021-05-28 07:59 UTC, ahcorde requested changes

2021-05-28 07:59 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_system.cpp
> +
remove this line, then it's good to go

2021-05-28 15:42 UTC, ahcorde requested changes
@kbogert  uncrustify is failing

2021-05-28 16:41 UTC, ahcorde approved these changes

2021-05-28 16:41 UTC, merged